In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as matlab

In [2]:
dataset=pd.read_csv("Hit or Flop movie Dataset.csv")
dataset

,S.No,Film Industry,Movie Name,Genre,Movie Release Date,Investment,Investment.1,Profit,Profit.1,Success/Failure,...,Pre-released song views.1,first song released date,YouTube Views.2,YouTube Views.3,OTT,Rating_Type,Meme Marketing,Critics_from_people,First day Box office collection,First day Box office collection.1
0,1,Kollywood,Vikram,Action,03-06-2022,450 Crore,4500000000,150 Crore,1500000000,1,...,98000000,15-05-2022,50 Million,50000000,Netflix,Good,yes,Good,33 Crore,330000000
1,2,Kollywood,Sardar,Action,21-10-2022,40 Crore,400000000,100 Crore,1000000000,1,...,4000000,18-11-2022,11 Million,11000000,Netflix,Good,yes,Good,3.7 Crore,37000000
2,3,Kollywood,Beast,Action,13-04-2022,150 Crore,1500000000,250 Crore,2500000000,1,...,33000000,14-02-2022,48 Million,48000000,Netflix,Average,yes,Average,40 Crore,400000000
3,4,Kollywood,Pizza,Horror,19-10-2012,1.5 Crore,15000000,8 Crore,80000000,1,...,176000,06-09-2012,250 Thousand,250000,Netflix,Good,yes,Good,1.5 Crore,15000000
4,5,Kollywood,Naduvula Konjum Pakkatha kanum,Comedy,30-11-2012,0.8 Crore,8000000,18 Crore,180000000,1,...,49000,27-06-2012,30 Thousand,30000,Netflix,Good,Yes,Good,5 Crore,50000000
5,6,Kollywood,Don,Comedy,13-05-2022,5 Crore,50000000,100 Crore,1000000000,1,...,98000000,16-12-2021,47 Million,47000000,Netflix,Good,yes,Good,15 Crore,150000000
6,7,Kollywood,Doctor,Action,09-10-2021,40 Crore,400000000,100 Crore,1000000000,1,...,34000000,02-10-2021,41 Million,41000000,Netflix,Good,yes,Good,8 Crore,80000000
7,8,Kollywood,Ponniyin selvan-1,Action,30-09-2022,500 Crore,5000000000,495 Crore,4950000000,1,...,62000000,31-07-2022,50 Million,50000000,Netflix,Very good,Yes,Very Good,34 Crore,340000000
8,9,Kollywood,Maanaadu,Action,25-11-2021,30 Crore,300000000,117 Crore,1170000000,1,...,38000000,21-06-2021,18 Million,18000000,Netflix,Good,Yes,Good,8 Crore,80000000
9,10,Kollywood,Master,Action,13-01-2021,135 Crore,1350000000,300 Crore,3000000000,1,...,112000000,15-03-2020,406 Million,406000000,Netflix,Good,yes,Good,18 Crore,180000000
10,11,Kollywood,Soorarai pottru,Drama,12-11-2020,20 Crore,200000000,174 Crore,1740000000,1,...,16000000,24-01-2020,85 Million,85000000,Netflix,Good,yes,Good,8 Crore,80000000
11,12,Kollywood,Theeran Adhigaram ondru,Action,17-11-2017,50 Crore,500000000,85 Crore,850000000,1,...,40000,13-11-2017,12.9 Thousand,12900,Netflix,Good,yes,Good,10 Crore,100000000
12,13,Kollywood,Ka Pae Ranasingam,Drama,02-10-2020,10 Crore,100000000,9 Crore,90000000,1,...,100000,10-10-2020,8.3 Million,8300000,Netflix,Good,yes,Good,8 Crore,80000000
13,14,Kollywood,Karnan,Action,09-04-2021,10 Crore,100000000,63 Crore,630000000,1,...,21000000,19-02-2021,19.5 Million,19500000,Netflix,Good,yes,Good,10 Crore,100000000
14,15,Kollywood,Asuran,Action,04-10-2019,32 Crore,320000000,155 Crore,1550000000,1,...,23000000,18-09-2021,32 Million,32000000,Netflix,Good,yes,Good,10 Crore,100000000
15,16,Kollywood,2.0,Action,29-11-2018,600 Crore,6000000000,800 Crore,8000000000,1,...,14000000,27-10-2017,7.9 Million,7900000,Netflix,Good,yes,Good,82 Crore,820000000
16,17,Kollywood,24,Action,06-05-2016,70 Crore,700000000,100 Crore,1000000000,1,...,2000000,10-02-2016,8 Million,8000000,Netflix,Good,yes,Good,33 Crore,330000000
17,18,Kollywood,English vinglish,Comedy,05-10-2012,10 Crore,100000000,102 Crore,1020000000,1,...,4100000,14-09-2012,3 Million,3000000,Netflix,Good,yes,Good,2.5 Crore,25000000
18,19,Kollywood,Viswaroopam,Action,07-02-2013,95 Crore,950000000,220 Crore,2200000000,1,...,350000,11-02-2013,6.8 Million,6800000,Netflix,Good,yes,Good,10 Crore,100000000
19,20,Kollywood,Kaththi,Action,22-10-2014,70 Crore,700000000,130 Crore,1300000000,1,...,1200000,17-10-2014,587 Thousand,587000,Netflix,Good,yes,Good,15 Crore,150000000
20,21,Kollywood,Mahanati,Drama,09-05-2018,25 Crore,250000000,83 Crore,830000000,1,...,1200000,01-05-2018,101 Thousand,101000,Netflix,Good,yes,Good,5.9 Crore,59000000
21,22,Kollywood,Baahubali-The beginning,Action,10-07-2015,180 Crore,1800000000,650 Crore,6500000000,1,...,1800000,07-06-2015,19.5 Million,195000000,Netflix,Good,yes,Good,6 Crore,60000000
22,23,Kollywood,Enthiran,Action,01-10-2010,150 Crore,1500000000,290 Crore,2900000000,1,...,6000000,31-07-2010,1.4 Million,1400000,Netflix,Good,yes,Good,100 Crore,1000000000
23,24,Kollywood,Kakka muttai,Comedy,05-06-2015,1 Crore,10000000,12 Crore,120000000,1,...,150000,04-05-2015,451 Thousand,451000,Netflix,Good,yes,Good,2.4 Crore,24000000
24,25,Kollywood,Jai Bhim,Drama,02-11-2021,40 Crore,400000000,100 Crore,1000000000,1,...,19000000,30-10-2021,17 Million,17000000,Netflix,Good,yes,Good,6 Crore,60000000
25,26,Kollywood,Aayirathil Oruvan,Action,14-01-2010,18 Crore,180000000,10 Crore,100000000,0,...,148000,04-06-2009,164 Thousand,164000,Netflix,Good,yes,Good,1 Crore,10000000
26,27,Kollywood,NGK,Action,31-05-2019,65 Crore,650000000,30 Crore,300000000,0,...,1000000,19-04-2019,2.9 Million,2900000,Netflix,Bad,yes,Bad,14 Crore,140000000
27,28,Kollywood,Bhoomi,Action,14-01-2021,30 Crore,300000000,15 Crore,150000000,0,...,2000000,18-10-2020,4 Million,4000000,Netflix,Bad,yes,Bad,2 Crore,20000000
28,29,Kollywood,Thodari,Action,22-09-2016,40 Crore,400000000,23 Crore,230000000,0,...,2100000,06-06-2016,7.4 Million,7400000,Netflix,Bad,yes,Bad,4.32 Crore,43200000
29,30,Kollywood,Prince,Comedy,21-10-2022,60 Crore,600000000,22 Crore,220000000,0,...,1000000,30-09-2022,27 Million,27000000,Netflix,Bad,yes,Bad,6 Crore,60000000
30,31,Kollywood,Seema Raja,Action,13-09-2018,60 Crore,600000000,49 Crore,490000000,0,...,31000000,13-09-2018,73 Million,73000000,Netflix,Bad,yes,Bad,1.3 Crore,13000000
31,32,Kollywood,Saamy Square,Action,21-09-2018,50 Crore,500000000,38 Crore,380000000,0,...,2400000,10-07-2018,93 Million,93000000,Netflix,Bad,yes,Bad,60 lakh,6000000
32,33,Kollywood,Dev,Action,14-02-2019,40 Crore,400000000,25 Crore,250000000,0,...,2000000,07-02-2019,4.6 Million,4600000,Netflix,Bad,yes,Bad,60 lakh,6000000
33,34,Kollywood,Puli,Action,01-10-2015,130 Crore,1300000000,100 Crore,1000000000,0,...,11000000,02-08-2015,23 Million,23000000,Netflix,Bad,yes,Bad,10 Crore,100000000
34,35,Kollywood,Adhavan,Action,17-10-2009,30 Crore,300000000,20 Crore,200000000,0,...,5000000,20-08-2009,17 Thousand,17000,Netflix,Bad,yes,Bad,2.3 Crore,23000000
35,36,Kollywood,Alex pandian,Action,11-01-2013,17 Crore,170000000,12 Crore,120000000,0,...,225000,12-12-2012,5.6 Million,5600000,Netflix,Bad,yes,Bad,2 Crore,20000000
36,37,Kollywood,Naiyandi,Comedy,11-10-2013,20 Crore,200000000,16 Crore,160000000,0,...,1300000,17-09-2013,3.2 Million,3200000,Netflix,Bad,yes,Bad,1 Crore,10000000
37,38,Kollywood,Manmadhan Ambu,Comedy,22-12-2010,50 Crore,500000000,30 Crore,300000000,0,...,440000,25-11-2010,20 Million,20000000,Netflix,Bad,yes,Bad,5 Crore,50000000
38,39,Kollywood,Sura,Action,30-04-2010,30 Crore,300000000,40 Crore,400000000,0,...,12000,25-04-2010,10 Million,10000000,Netflix,Bad,yes,Bad,2 Crore,20000000
39,40,Kollywood,Asal,Action,05-02-2010,22 Crore,220000000,12 Crore,120000000,0,...,34000,20-01-2010,100 Thousand,100000,Netflix,Bad,yes,Bad,2 Crore,20000000
40,41,Kollywood,Rekka,Action,07-10-2016,10 Crore,100000000,14 Crore,140000000,0,...,2000000,30-09-2016,7 Million,7000000,Netflix,Bad,yes,Bad,6 Crore,60000000
41,42,Kollywood,Vanamagan,Action,23-06-2017,18 Crore,180000000,10 Crore,100000000,0,...,2000000,22-04-2017,12 Million,12000000,Netflix,Bad,yes,Bad,2 Crore,20000000
42,43,Kollywood,Hero,Superhero,20-12-2019,45 Crore,450000000,40 Crore,400000000,0,...,2800000,29-11-2019,30 Million,30000000,Netflix,Bad,yes,Bad,1.31 Crore,13100000
43,44,Kollywood,Action,Action,15-11-2019,40 Crore,400000000,35 Crore,350000000,0,...,4200000,09-11-2019,5.4 Million,5400000,Netflix,Bad,yes,Bad,1 Crore,10000000
44,45,Kollywood,Ravanan,Action,18-06-2010,55 Crore,550000000,50 Crore,500000000,0,...,2000000,07-05-2010,38 Million,38000000,Netflix,Bad,yes,Bad,6 Crore,60000000
45,46,Kollywood,Cobra,Action,31-08-2022,100 Crore,1000000000,60 Crore,600000000,0,...,6200000,09-08-2022,29 Million,29000000,Netflix,Bad,yes,Bad,24 Crore,240000000
46,47,Kollywood,Mappillai,Action,08-04-2011,33 Crore,330000000,32 Crore,320000000,0,...,30000000,30-03-2011,4.4 Million,4400000,Netflix,Bad,yes,Bad,5 Crore,50000000
47,48,Kollywood,Uttama villan,Comedy,02-05-2015,50 Crore,500000000,26 Crore,260000000,0,...,657000,01-03-2015,2 Million,2000000,Netflix,Bad,yes,Bad,`10 Crore,100000000
48,49,Kollywood,Kochadaiyan,Action,23-05-2014,125 Crore,1250000000,42 Crore,420000000,0,...,1000000,09-03-2014,13 Million,13000000,Netflix,Bad,yes,Bad,6 Crore,60000000
49,50,Kollywood,Anjaan,Action,15-08-2014,75 Crore,750000000,45 Crore,450000000,0,...,16000000,10-08-2014,16 Million,16000000,Netflix,Bad,yes,Bad,1 Crore,10000000

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,S.No,Investment.1,Profit.1,Success/Failure,IMDb Rating,YouTube Views.1,Common Background music,Theme background Music,No.of Part Released,Comedy Scene,...,First day Box office collection_34 Crore,First day Box office collection_4.32 Crore,First day Box office collection_40 Crore,First day Box office collection_5 Crore,First day Box office collection_5.9 Crore,First day Box office collection_6 Crore,First day Box office collection_60 lakh,First day Box office collection_8 Crore,First day Box office collection_82 Crore,First day Box office collection_`10 Crore
0,1,4500000000,1500000000,1,8.4,43000000,1,0,5,1,...,0,0,0,0,0,0,0,0,0,0
1,2,400000000,1000000000,1,7.8,10000000,0,1,4,1,...,0,0,0,0,0,0,0,0,0,0
2,3,1500000000,2500000000,1,5.6,59000000,0,1,4,1,...,0,0,1,0,0,0,0,0,0,0
3,4,15000000,80000000,1,8.0,309000,0,1,2,1,...,0,0,0,0,0,0,0,0,0,0
4,5,8000000,180000000,1,8.2,80000,1,0,3,1,...,0,0,0,1,0,0,0,0,0,0
5,6,50000000,1000000000,1,6.9,14000000,1,1,5,1,...,0,0,0,0,0,0,0,0,0,0
6,7,400000000,1000000000,1,7.4,14000000,0,1,4,1,...,0,0,0,0,0,0,0,1,0,0
7,8,5000000000,4950000000,1,9.4,18000000,0,1,3,1,...,1,0,0,0,0,0,0,0,0,0
8,9,300000000,1170000000,1,8.3,15000000,0,1,5,1,...,0,0,0,0,0,0,0,1,0,0
9,10,1350000000,3000000000,1,7.3,59000000,0,1,4,1,...,0,0,0,0,0,0,0,0,0,0
10,11,200000000,1740000000,1,8.7,28000000,0,1,5,1,...,0,0,0,0,0,0,0,1,0,0
11,12,500000000,850000000,1,8.2,1100000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0
12,13,100000000,90000000,1,7.3,45000000,1,0,4,1,...,0,0,0,0,0,0,0,0,0,0
13,14,100000000,630000000,1,8.0,19000000,1,0,4,1,...,0,0,0,0,0,0,0,0,0,0
14,15,320000000,1550000000,1,8.4,14000000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0
15,16,6000000000,8000000000,1,6.1,23000000,0,1,3,1,...,0,0,0,0,0,0,0,0,1,0
16,17,700000000,1000000000,1,7.8,6800000,1,0,4,1,...,0,0,0,0,0,0,0,0,0,0
17,18,100000000,1020000000,1,7.8,997000,1,0,4,1,...,0,0,0,0,0,0,0,0,0,0
18,19,950000000,2200000000,1,7.9,349000,0,1,4,1,...,0,0,0,0,0,0,0,0,0,0
19,20,700000000,1300000000,1,8.0,8800000,0,1,5,1,...,0,0,0,0,0,0,0,0,0,0
20,21,250000000,830000000,1,8.5,843000,1,0,3,1,...,0,0,0,0,1,0,0,0,0,0
21,22,1800000000,6500000000,1,8.0,5300000,0,1,4,1,...,0,0,0,0,0,1,0,0,0,0
22,23,1500000000,2900000000,1,7.1,414000,0,1,3,1,...,0,0,0,0,0,0,0,0,0,0
23,24,10000000,120000000,1,8.3,3000000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0
24,25,400000000,1000000000,1,8.9,24000000,0,1,4,1,...,0,0,0,0,0,1,0,0,0,0
25,26,180000000,100000000,0,8.0,213000,0,1,3,1,...,0,0,0,0,0,0,0,0,0,0
26,27,650000000,300000000,0,5.8,13000000,0,1,4,1,...,0,0,0,0,0,0,0,0,0,0
27,28,300000000,150000000,0,4.7,4200000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0
28,29,400000000,230000000,0,4.6,4300000,1,0,3,1,...,0,1,0,0,0,0,0,0,0,0
29,30,600000000,220000000,0,4.6,9000000,1,0,3,1,...,0,0,0,0,0,1,0,0,0,0
30,31,600000000,490000000,0,4.2,10000000,1,0,5,1,...,0,0,0,0,0,0,0,0,0,0
31,32,500000000,380000000,0,4.5,19000000,1,0,4,1,...,0,0,0,0,0,0,1,0,0,0
32,33,400000000,250000000,0,4.8,4600000,1,0,3,1,...,0,0,0,0,0,0,1,0,0,0
33,34,1300000000,1000000000,0,4.3,10000000,0,1,3,1,...,0,0,0,0,0,0,0,0,0,0
34,35,300000000,200000000,0,5.4,86000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0
35,36,170000000,120000000,0,2.8,780000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0
36,37,200000000,160000000,0,3.4,94000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0
37,38,500000000,300000000,0,5.6,350000,1,0,3,1,...,0,0,0,1,0,0,0,0,0,0
38,39,300000000,400000000,0,3.0,156000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0
39,40,220000000,120000000,0,3.7,68000,0,1,3,1,...,0,0,0,0,0,0,0,0,0,0
40,41,100000000,140000000,0,5.0,3000000,0,1,3,1,...,0,0,0,0,0,1,0,0,0,0
41,42,180000000,100000000,0,5.5,4900000,0,1,4,1,...,0,0,0,0,0,0,0,0,0,0
42,43,450000000,400000000,0,6.3,8400000,0,1,3,1,...,0,0,0,0,0,0,0,0,0,0
43,44,400000000,350000000,0,4.6,9400000,1,0,4,1,...,0,0,0,0,0,0,0,0,0,0
44,45,550000000,500000000,0,6.9,95000,1,0,3,1,...,0,0,0,0,0,1,0,0,0,0
45,46,1000000000,600000000,0,6.2,26000000,0,1,3,1,...,0,0,0,0,0,0,0,0,0,0
46,47,330000000,320000000,0,3.2,380000,1,0,3,1,...,0,0,0,1,0,0,0,0,0,0
47,48,500000000,260000000,0,7.3,1000000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,1
48,49,1250000000,420000000,0,6.2,489000,0,1,3,1,...,0,0,0,0,0,1,0,0,0,0
49,50,750000000,450000000,0,5.1,5200000,1,0,3,1,...,0,0,0,0,0,0,0,0,0,0

In [4]:
dataset.columns

Index(['S.No', 'Investment.1', 'Profit.1', 'Success/Failure', 'IMDb Rating',
       'YouTube Views.1', 'Common Background music', 'Theme background Music',
       'No.of Part Released', 'Comedy Scene',
       ...
       'First day Box office collection_34 Crore',
       'First day Box office collection_4.32 Crore',
       'First day Box office collection_40 Crore',
       'First day Box office collection_5 Crore',
       'First day Box office collection_5.9 Crore',
       'First day Box office collection_6 Crore',
       'First day Box office collection_60 lakh',
       'First day Box office collection_8 Crore',
       'First day Box office collection_82 Crore',
       'First day Box office collection_`10 Crore'],
      dtype='object', length=585)

In [5]:
independent=dataset[['Investment.1',"Profit.1", 'IMDb Rating',
       'YouTube Views.1', 'Common Background music', 'Theme background Music',
       'No.of Part Released', 'Comedy Scene',"Fast mode","Slow mode","Medium mode",
                     "Pre-released song views.1","YouTube Views.3",
       'First day Box office collection_34 Crore',
       'First day Box office collection_4.32 Crore',
       'First day Box office collection_40 Crore',
       'First day Box office collection_5 Crore',
       'First day Box office collection_5.9 Crore',
       'First day Box office collection_6 Crore',
       'First day Box office collection_60 lakh',
       'First day Box office collection_8 Crore',
       'First day Box office collection_82 Crore',
       'First day Box office collection_`10 Crore']]
dependent=dataset[['Success/Failure']]

In [6]:
independent.shape

(50, 23)

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestClassifier

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:284: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_Gram=True, verbose=0,
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:1101: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:1127: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, positive=False):
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:1362: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:1602: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\least_angle.py:1738: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\decomposition\online_lda.py:29: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  EPS = np.finfo(np.float).eps
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\gradient_boosting.py:32: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\gradient_boosting.py:32: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages

In [10]:
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy'],'max_features':['auto','sqrt','log2']}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
#fitting the model for grid search
grid.fit(X_train,Y_train)

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:670: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_folds = np.zeros(n_samples, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:442: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  fold_sizes = np.full(n_splits, n_samples // n_splits, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:442: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  fold_sizes = np.full(n_splits, n_samples // n_splits, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 6 candidates, totalling 18 fits

[Parallel(n_jobs=-1)]: Done  18 out of  18 | elapsed:    5.2s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  18 out of  18 | elapsed:    5.2s finished
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_search.py:794: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\model_selection\_search.py:715: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\forest.py:489: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_store_unique_indices = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [11]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
classifier.fit(X_train,Y_train)

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\forest.py:489: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_store_unique_indices = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [12]:
y_pred=classifier.predict(X_test)

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [13]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [14]:
re=grid.cv_results_
grid_predictions=grid.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,y_pred)

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [15]:
print(cm)

[[9 0]
 [1 7]]

In [16]:
from sklearn.metrics import classification_report
clf_report=classification_report(Y_test,y_pred)

In [17]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.90      1.00      0.95         9
           1       1.00      0.88      0.93         8

    accuracy                           0.94        17
   macro avg       0.95      0.94      0.94        17
weighted avg       0.95      0.94      0.94        17

In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

0.9375

In [19]:
classifier.predict([[300000000,500000000,7.0,2000000,0,1,4,1,0,0,1,1000000,2000000,0,1,0,0,0,0,0,0,0,0]])

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

array([1], dtype=int64)

In [20]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.070146,0.000470,0.010971,0.000815,gini,auto,"{'criterion': 'gini', 'max_features': 'auto'}",0.916084,0.815152,1.000000,0.907869,0.073907,1
1,0.055851,0.013105,0.007314,0.001881,gini,sqrt,"{'criterion': 'gini', 'max_features': 'sqrt'}",0.748252,0.815152,1.000000,0.846839,0.104774,6
2,0.051861,0.008266,0.009309,0.002859,gini,log2,"{'criterion': 'gini', 'max_features': 'log2'}",1.000000,0.815152,0.791667,0.875253,0.094763,5
3,0.052526,0.003762,0.006982,0.001411,entropy,auto,"{'criterion': 'entropy', 'max_features': 'auto'}",0.916084,0.909091,0.800000,0.878576,0.051893,2
4,0.053856,0.005642,0.005651,0.000470,entropy,sqrt,"{'criterion': 'entropy', 'max_features': 'sqrt'}",0.916084,0.907537,0.791667,0.875533,0.055414,4
5,0.048205,0.004630,0.005652,0.000940,entropy,log2,"{'criterion': 'entropy', 'max_features': 'log2'}",1.000000,0.815152,0.800000,0.877778,0.092588,3

In [21]:
inves_input=int(input("Investment :"))
profit_input=int(input("Profit :"))
imdb_input=float(input("IMDb rating :"))
youtubeViews_input=int(input("Youtube Trailer Views :"))
commonMusic_input=int(input("Common Background music :"))
ThemeMusic_input=int(input("Theme Background music :"))
partRelease_input=int(input("No. of part released :"))
comScene_input=int(input("Comedy scene :"))
fasmode_input=int(input("Fast Mode:"))
slowmode_input=int(input("Slow Mode:"))
medmode_input=int(input("Medium Mode:"))
prereleasesongviews_input=int(input("Pre-release song views :"))
youtubeviews3_input=int(input("Youtube Song views"))
fdc34Crore_input=int(input("First day box Office collection 34 crore :"))
fdc4_32crore_input=int(input("First day box Office collection 4.32 crore :"))
fdc40crore_input=int(input("First day box Office collection 40 crore :"))
fdc5crore_input=int(input("First day box Office collection 5 crore :"))
fdc5_9crore_input=int(input("First day box Office collection 5.9 crore :"))
fdc6crore_input=int(input("First day box Office collection 6 crore :"))
fdc60lakh_input=int(input("First day box Office collection 60 lakh :"))
fdc8crore_input=int(input("First day box Office collection 8 crore :"))
fdc82crore_input=int(input("First day box Office collection 82 crore :"))
fdc10crore_input=int(input("First day box Office collection 10 crore :"))

Investment :300000000
Profit :500000000
IMDb rating :7.0
Youtube Trailer Views :2000000
Common Background music :0
Theme Background music :1
No. of part released :4
Comedy scene :1
Fast Mode:0
Slow Mode:0
Medium Mode:1
Pre-release song views :10000000
Youtube Song views20000000
First day box Office collection 34 crore :0
First day box Office collection 4.32 crore :1
First day box Office collection 40 crore :0
First day box Office collection 5 crore :0
First day box Office collection 5.9 crore :0
First day box Office collection 6 crore :0
First day box Office collection 60 lakh :0
First day box Office collection 8 crore :0
First day box Office collection 82 crore :0
First day box Office collection 10 crore :0

In [22]:
success_failure_Prediction=grid.predict([[inves_input,profit_input,imdb_input,youtubeViews_input,commonMusic_input,ThemeMusic_input,partRelease_input,comScene_input,
                                 fasmode_input,slowmode_input,medmode_input,prereleasesongviews_input,youtubeviews3_input,fdc34Crore_input,fdc4_32crore_input,fdc40crore_input,fdc5crore_input,fdc5_9crore_input,fdc6crore_input,fdc60lakh_input,fdc8crore_input,fdc82crore_input,fdc10crore_input]])
print("Success/Failure Prediction={}".format(success_failure_Prediction))

Success/Failure Prediction=[1]

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [23]:
#pickle is used to save model creation
import pickle
#Create filename,it is pickle extension so we save .sav
filename="finalized_model_randomforest.sav"

In [24]:
pickle.dump(classifier, open(filename,"wb"))

In [26]:
#load the model and rb is used for just read 
loaded_model=pickle.load(open("finalized_model_randomforest.sav","rb"))
#we check it and for prediction we can do it
result=loaded_model.predict([[300000000,500000000,7.0,2000000,0,1,4,1,0,0,1,1000000,2000000,0,1,0,0,0,0,0,0,0,0]])

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\ensemble\base.py:158: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [27]:
result

array([1], dtype=int64)