In [48]:
import pandas as pd
import numpy as np
dataset=pd.read_csv("Hit or Flop movie Dataset.csv")
dataset

,S.No,Film Industry,Movie Name,Genre,Movie Release Date,Investment,Investment.1,Profit,Profit.1,Success/Failure,...,Pre-released song views.1,first song released date,YouTube Views.2,YouTube Views.3,OTT,Rating_Type,Meme Marketing,Critics_from_people,First day Box office collection,First day Box office collection.1
0,1,Kollywood,Vikram,Action,03-06-2022,450 Crore,4500000000,150 Crore,1500000000,1,...,98000000,15-05-2022,50 Million,50000000,Netflix,Good,yes,Good,33 Crore,330000000
1,2,Kollywood,Sardar,Action,21-10-2022,40 Crore,400000000,100 Crore,1000000000,1,...,4000000,18-11-2022,11 Million,11000000,Netflix,Good,yes,Good,3.7 Crore,37000000
2,3,Kollywood,Beast,Action,13-04-2022,150 Crore,1500000000,250 Crore,2500000000,1,...,33000000,14-02-2022,48 Million,48000000,Netflix,Average,yes,Average,40 Crore,400000000
3,4,Kollywood,Pizza,Horror,19-10-2012,1.5 Crore,15000000,8 Crore,80000000,1,...,176000,06-09-2012,250 Thousand,250000,Netflix,Good,yes,Good,1.5 Crore,15000000
4,5,Kollywood,Naduvula Konjum Pakkatha kanum,Comedy,30-11-2012,0.8 Crore,8000000,18 Crore,180000000,1,...,49000,27-06-2012,30 Thousand,30000,Netflix,Good,Yes,Good,5 Crore,50000000
5,6,Kollywood,Don,Comedy,13-05-2022,5 Crore,50000000,100 Crore,1000000000,1,...,98000000,16-12-2021,47 Million,47000000,Netflix,Good,yes,Good,15 Crore,150000000
6,7,Kollywood,Doctor,Action,09-10-2021,40 Crore,400000000,100 Crore,1000000000,1,...,34000000,02-10-2021,41 Million,41000000,Netflix,Good,yes,Good,8 Crore,80000000
7,8,Kollywood,Ponniyin selvan-1,Action,30-09-2022,500 Crore,5000000000,495 Crore,4950000000,1,...,62000000,31-07-2022,50 Million,50000000,Netflix,Very good,Yes,Very Good,34 Crore,340000000
8,9,Kollywood,Maanaadu,Action,25-11-2021,30 Crore,300000000,117 Crore,1170000000,1,...,38000000,21-06-2021,18 Million,18000000,Netflix,Good,Yes,Good,8 Crore,80000000
9,10,Kollywood,Master,Action,13-01-2021,135 Crore,1350000000,300 Crore,3000000000,1,...,112000000,15-03-2020,406 Million,406000000,Netflix,Good,yes,Good,18 Crore,180000000
10,11,Kollywood,Soorarai pottru,Drama,12-11-2020,20 Crore,200000000,174 Crore,1740000000,1,...,16000000,24-01-2020,85 Million,85000000,Netflix,Good,yes,Good,8 Crore,80000000
11,12,Kollywood,Theeran Adhigaram ondru,Action,17-11-2017,50 Crore,500000000,85 Crore,850000000,1,...,40000,13-11-2017,12.9 Thousand,12900,Netflix,Good,yes,Good,10 Crore,100000000
12,13,Kollywood,Ka Pae Ranasingam,Drama,02-10-2020,10 Crore,100000000,9 Crore,90000000,1,...,100000,10-10-2020,8.3 Million,8300000,Netflix,Good,yes,Good,8 Crore,80000000
13,14,Kollywood,Karnan,Action,09-04-2021,10 Crore,100000000,63 Crore,630000000,1,...,21000000,19-02-2021,19.5 Million,19500000,Netflix,Good,yes,Good,10 Crore,100000000
14,15,Kollywood,Asuran,Action,04-10-2019,32 Crore,320000000,155 Crore,1550000000,1,...,23000000,18-09-2021,32 Million,32000000,Netflix,Good,yes,Good,10 Crore,100000000
15,16,Kollywood,2.0,Action,29-11-2018,600 Crore,6000000000,800 Crore,8000000000,1,...,14000000,27-10-2017,7.9 Million,7900000,Netflix,Good,yes,Good,82 Crore,820000000
16,17,Kollywood,24,Action,06-05-2016,70 Crore,700000000,100 Crore,1000000000,1,...,2000000,10-02-2016,8 Million,8000000,Netflix,Good,yes,Good,33 Crore,330000000
17,18,Kollywood,English vinglish,Comedy,05-10-2012,10 Crore,100000000,102 Crore,1020000000,1,...,4100000,14-09-2012,3 Million,3000000,Netflix,Good,yes,Good,2.5 Crore,25000000
18,19,Kollywood,Viswaroopam,Action,07-02-2013,95 Crore,950000000,220 Crore,2200000000,1,...,350000,11-02-2013,6.8 Million,6800000,Netflix,Good,yes,Good,10 Crore,100000000
19,20,Kollywood,Kaththi,Action,22-10-2014,70 Crore,700000000,130 Crore,1300000000,1,...,1200000,17-10-2014,587 Thousand,587000,Netflix,Good,yes,Good,15 Crore,150000000
20,21,Kollywood,Mahanati,Drama,09-05-2018,25 Crore,250000000,83 Crore,830000000,1,...,1200000,01-05-2018,101 Thousand,101000,Netflix,Good,yes,Good,5.9 Crore,59000000
21,22,Kollywood,Baahubali-The beginning,Action,10-07-2015,180 Crore,1800000000,650 Crore,6500000000,1,...,1800000,07-06-2015,19.5 Million,195000000,Netflix,Good,yes,Good,6 Crore,60000000
22,23,Kollywood,Enthiran,Action,01-10-2010,150 Crore,1500000000,290 Crore,2900000000,1,...,6000000,31-07-2010,1.4 Million,1400000,Netflix,Good,yes,Good,100 Crore,1000000000
23,24,Kollywood,Kakka muttai,Comedy,05-06-2015,1 Crore,10000000,12 Crore,120000000,1,...,150000,04-05-2015,451 Thousand,451000,Netflix,Good,yes,Good,2.4 Crore,24000000
24,25,Kollywood,Jai Bhim,Drama,02-11-2021,40 Crore,400000000,100 Crore,1000000000,1,...,19000000,30-10-2021,17 Million,17000000,Netflix,Good,yes,Good,6 Crore,60000000
25,26,Kollywood,Aayirathil Oruvan,Action,14-01-2010,18 Crore,180000000,10 Crore,100000000,0,...,148000,04-06-2009,164 Thousand,164000,Netflix,Good,yes,Good,1 Crore,10000000
26,27,Kollywood,NGK,Action,31-05-2019,65 Crore,650000000,30 Crore,300000000,0,...,1000000,19-04-2019,2.9 Million,2900000,Netflix,Bad,yes,Bad,14 Crore,140000000
27,28,Kollywood,Bhoomi,Action,14-01-2021,30 Crore,300000000,15 Crore,150000000,0,...,2000000,18-10-2020,4 Million,4000000,Netflix,Bad,yes,Bad,2 Crore,20000000
28,29,Kollywood,Thodari,Action,22-09-2016,40 Crore,400000000,23 Crore,230000000,0,...,2100000,06-06-2016,7.4 Million,7400000,Netflix,Bad,yes,Bad,4.32 Crore,43200000
29,30,Kollywood,Prince,Comedy,21-10-2022,60 Crore,600000000,22 Crore,220000000,0,...,1000000,30-09-2022,27 Million,27000000,Netflix,Bad,yes,Bad,6 Crore,60000000
30,31,Kollywood,Seema Raja,Action,13-09-2018,60 Crore,600000000,49 Crore,490000000,0,...,31000000,13-09-2018,73 Million,73000000,Netflix,Bad,yes,Bad,1.3 Crore,13000000
31,32,Kollywood,Saamy Square,Action,21-09-2018,50 Crore,500000000,38 Crore,380000000,0,...,2400000,10-07-2018,93 Million,93000000,Netflix,Bad,yes,Bad,60 lakh,6000000
32,33,Kollywood,Dev,Action,14-02-2019,40 Crore,400000000,25 Crore,250000000,0,...,2000000,07-02-2019,4.6 Million,4600000,Netflix,Bad,yes,Bad,60 lakh,6000000
33,34,Kollywood,Puli,Action,01-10-2015,130 Crore,1300000000,100 Crore,1000000000,0,...,11000000,02-08-2015,23 Million,23000000,Netflix,Bad,yes,Bad,10 Crore,100000000
34,35,Kollywood,Adhavan,Action,17-10-2009,30 Crore,300000000,20 Crore,200000000,0,...,5000000,20-08-2009,17 Thousand,17000,Netflix,Bad,yes,Bad,2.3 Crore,23000000
35,36,Kollywood,Alex pandian,Action,11-01-2013,17 Crore,170000000,12 Crore,120000000,0,...,225000,12-12-2012,5.6 Million,5600000,Netflix,Bad,yes,Bad,2 Crore,20000000
36,37,Kollywood,Naiyandi,Comedy,11-10-2013,20 Crore,200000000,16 Crore,160000000,0,...,1300000,17-09-2013,3.2 Million,3200000,Netflix,Bad,yes,Bad,1 Crore,10000000
37,38,Kollywood,Manmadhan Ambu,Comedy,22-12-2010,50 Crore,500000000,30 Crore,300000000,0,...,440000,25-11-2010,20 Million,20000000,Netflix,Bad,yes,Bad,5 Crore,50000000
38,39,Kollywood,Sura,Action,30-04-2010,30 Crore,300000000,40 Crore,400000000,0,...,12000,25-04-2010,10 Million,10000000,Netflix,Bad,yes,Bad,2 Crore,20000000
39,40,Kollywood,Asal,Action,05-02-2010,22 Crore,220000000,12 Crore,120000000,0,...,34000,20-01-2010,100 Thousand,100000,Netflix,Bad,yes,Bad,2 Crore,20000000
40,41,Kollywood,Rekka,Action,07-10-2016,10 Crore,100000000,14 Crore,140000000,0,...,2000000,30-09-2016,7 Million,7000000,Netflix,Bad,yes,Bad,6 Crore,60000000
41,42,Kollywood,Vanamagan,Action,23-06-2017,18 Crore,180000000,10 Crore,100000000,0,...,2000000,22-04-2017,12 Million,12000000,Netflix,Bad,yes,Bad,2 Crore,20000000
42,43,Kollywood,Hero,Superhero,20-12-2019,45 Crore,450000000,40 Crore,400000000,0,...,2800000,29-11-2019,30 Million,30000000,Netflix,Bad,yes,Bad,1.31 Crore,13100000
43,44,Kollywood,Action,Action,15-11-2019,40 Crore,400000000,35 Crore,350000000,0,...,4200000,09-11-2019,5.4 Million,5400000,Netflix,Bad,yes,Bad,1 Crore,10000000
44,45,Kollywood,Ravanan,Action,18-06-2010,55 Crore,550000000,50 Crore,500000000,0,...,2000000,07-05-2010,38 Million,38000000,Netflix,Bad,yes,Bad,6 Crore,60000000
45,46,Kollywood,Cobra,Action,31-08-2022,100 Crore,1000000000,60 Crore,600000000,0,...,6200000,09-08-2022,29 Million,29000000,Netflix,Bad,yes,Bad,24 Crore,240000000
46,47,Kollywood,Mappillai,Action,08-04-2011,33 Crore,330000000,32 Crore,320000000,0,...,30000000,30-03-2011,4.4 Million,4400000,Netflix,Bad,yes,Bad,5 Crore,50000000
47,48,Kollywood,Uttama villan,Comedy,02-05-2015,50 Crore,500000000,26 Crore,260000000,0,...,657000,01-03-2015,2 Million,2000000,Netflix,Bad,yes,Bad,`10 Crore,100000000
48,49,Kollywood,Kochadaiyan,Action,23-05-2014,125 Crore,1250000000,42 Crore,420000000,0,...,1000000,09-03-2014,13 Million,13000000,Netflix,Bad,yes,Bad,6 Crore,60000000
49,50,Kollywood,Anjaan,Action,15-08-2014,75 Crore,750000000,45 Crore,450000000,0,...,16000000,10-08-2014,16 Million,16000000,Netflix,Bad,yes,Bad,1 Crore,10000000

In [49]:
Q1 = dataset.quantile(0.25)
Q3 = dataset.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

S.No                                 2.450000e+01
Investment.1                         4.950000e+08
Profit.1                             7.925000e+08
Success/Failure                      1.000000e+00
IMDb Rating                          3.150000e+00
YouTube Views.1                      1.343825e+07
Common Background music              1.000000e+00
Theme background Music               1.000000e+00
No.of Part Released                  1.000000e+00
Comedy Scene                         0.000000e+00
Fast mode                            0.000000e+00
Slow mode                            0.000000e+00
Medium mode                          0.000000e+00
Pre-released song views.1            1.500000e+07
YouTube Views.3                      2.670000e+07
First day Box office collection.1    8.000000e+07
dtype: float64

In [50]:
print(dataset < (Q1 - 1.5 * IQR)) |(dataset > (Q3 + 1.5 * IQR))

    1st-30min  2nd-30mins  3rd-30mins  4th-30mins  5th-30mins  Comedy Scene  \
0       False       False       False       False       False         False
1       False       False       False       False       False         False
2       False       False       False       False       False         False
3       False       False       False       False       False         False
4       False       False       False       False       False         False
5       False       False       False       False       False         False
6       False       False       False       False       False         False
7       False       False       False       False       False         False
8       False       False       False       False       False         False
9       False       False       False       False       False         False
10      False       False       False       False       False         False
11      False       False       False       False       False         False
12      False       False       False       False       False         False
13      False       False       False       False       False         False
14      False       False       False       False       False         False
15      False       False       False       False       False         False
16      False       False       False       False       False         False
17      False       False       False       False       False         False
18      False       False       False       False       False         False
19      False       False       False       False       False         False
20      False       False       False       False       False         False
21      False       False       False       False       False         False
22      False       False       False       False       False         False
23      False       False       False       False       False         False
24      False       False       False       False       False         False
25      False       False       False       False       False         False
26      False       False       False       False       False         False
27      False       False       False       False       False         False
28      False       False       False       False       False         False
29      False       False       False       False       False         False
30      False       False       False       False       False         False
31      False       False       False       False       False         False
32      False       False       False       False       False         False
33      False       False       False       False       False         False
34      False       False       False       False       False         False
35      False       False       False       False       False         False
36      False       False       False       False       False         False
37      False       False       False       False       False         False
38      False       False       False       False       False         False
39      False       False       False       False       False         False
40      False       False       False       False       False         False
41      False       False       False       False       False         False
42      False       False       False       False       False         False
43      False       False       False       False       False         False
44      False       False       False       False       False         False
45      False       False       False       False       False         False
46      False       False       False       False       False         False
47      False       False       False       False       False         False
48      False       False       False       False       False         False
49      False       False       False       False       False         False

    Common Background music  Critics_from_people   Fast mode  Film Industry  \
0                     False                 False      False          False
1                     False                 False      False          False
2                     False                 False      False          False
3                     False                 False      False          False
4                     False                 False      False          False
5                     False                 False      False          False
6                     False                 False      False          False
7                     False                 False      False          False
8                     False                 False      False          False
9                     False                 False      False          False
10                    False                 False      False          False
11                    False                 False      False          False
12                    False                 False      False          False
13                    False                 False      False          False
14                    False                 False      False          False
15                    False                 False      False          False
16                    False                 False      False          False
17                    False                 False      False          False
18                    False                 False      False          False
19                    False                 False      False          False
20                    False                 False      False          False
21                    False                 False      False          False
22                    False                 False      False          False
23                    False                 False      False          False
24                    False                 False      False          False
25                    False                 False      False          False
26                    False                 False      False          False
27                    False                 False      False          False
28                    False                 False      False          False
29                    False                 False      False          False
30                    False                 False      False          False
31                    False                 False      False          False
32                    False                 False      False          False
33                    False                 False      False          False
34                    False                 False      False          False
35                    False                 False      False          False
36                    False                 False      False          False
37                    False                 False      False          False
38                    False                 False      False          False
39                    False                 False      False          False
40                    False                 False      False          False
41                    False                 False      False          False
42                    False                 False      False          False
43                    False                 False      False          False
44                    False                 False      False          False
45                    False                 False      False          False
46                    False                 False      False          False
47                    False                 False      False          False
48                    False                 False      False          False
49                    False                 False      False          False

    ...   S.No  Slow mode  Success/Failure  Theme background Music  \
0   ...  False      False            False                   False
1   ...  False      False            False                   False
2   ...  False      False            False                   False
3   ...  False      False            False                   False
4   ...  False      False            False                   False
5   ...  False      False            False                   False
6   ...  False      False            False                   False
7   ...  False      False            False                   False
8   ...  False      False            False                   False
9   ...  False      False            False                   False
10  ...  False      False            False                   False
11  ...  False      False            False                   False
12  ...  False      False            False                   False
13  ...  False      False            False                   False
14  ...  False      False            False                   False
15  ...  False      False            False                   False
16  ...  False      False            False                   False
17  ...  False      False            False                   False
18  ...  False      False            False                   False
19  ...  False      False            False                   False
20  ...  False      False            False                   False
21  ...  False      False            False                   False
22  ...  False      False            False                   False
23  ...  False      False            False                   False
24  ...  False      False            False                   False
25  ...  False      False            False                   False
26  ...  False      False            False                   False
27  ...  False      False            False                   False
28  ...  False      False            False                   False
29  ...  False      False            False                   False
30  ...  False      False            False                   False
31  ...  False      False            False                   False
32  ...  False      False            False                   False
33  ...  False      False            False                   False
34  ...  False      False            False                   False
35  ...  False      False            False                   False
36  ...  False      False            False                   False
37  ...  False      False            False                   False
38  ...  False      False            False                   False
39  ...  False      False            False                   False
40  ...  False      False            False                   False
41  ...  False      False            False                   False
42  ...  False      False            False                   False
43  ...  False      False            False                   False
44  ...  False      False            False                   False
45  ...  False      False            False                   False
46  ...  False      False            False                   False
47  ...  False      False            False                   False
48  ...  False      False            False                   False
49  ...  False      False            False                   False

    Trailer Released Date  YouTube Views  YouTube Views.1  YouTube Views.2  \
0                   False          False            False            False
1                   False          False            False            False
2                   False          False            False            False
3                   False          False            False            False
4                   False          False            False            False
5                   False          False            False            False
6                   False          False            False            False
7                   False          False            False            False
8                   False          False            False            False
9                   False          False            False            False
10                  False          False            False            False
11                  False          False            False            False
12                  False          False            False            False
13                  False          False            False            False
14                  False          False            False            False
15                  False          False            False            False
16                  False          False            False            False
17                  False          False            False            False
18                  False          False            False            False
19                  False          False            False            False
20                  False          False            False            False
21                  False          False            False            False
22                  False          False            False            False
23                  False          False            False            False
24                  False          False            False            False
25                  False          False            False            False
26                  False          False            False            False
27                  False          False            False            False
28                  False          False            False            False
29                  False          False            False            False
30                  False          False            False            False
31                  False          False            False            False
32                  False          False            False            False
33                  False          False            False            False
34                  False          False            False            False
35                  False          False            False            False
36                  False          False            False            False
37                  False          False            False            False
38                  False          False            False            False
39                  False          False            False            False
40                  False          False            False            False
41                  False          False            False            False
42                  False          False            False            False
43                  False          False            False            False
44                  False          False            False            False
45                  False          False            False            False
46                  False          False            False            False
47                  False          False            False            False
48                  False          False            False            False
49                  False          False            False            False

    YouTube Views.3  first song released date
0             False                     False
1             False                     False
2             False                     False
3             False                     False
4             False                     False
5             False                     False
6             False                     False
7             False                     False
8             False                     False
9             False                     False
10            False                     False
11            False                     False
12            False                     False
13            False                     False
14            False                     False
15            False                     False
16            False                     False
17            False                     False
18            False                     False
19            False                     False
20            False                     False
21            False                     False
22            False                     False
23            False                     False
24            False                     False
25            False                     False
26            False                     False
27            False                     False
28            False                     False
29            False                     False
30            False                     False
31            False                     False
32            False                     False
33            False                     False
34            False                     False
35            False                     False
36            False                     False
37            False                     False
38            False                     False
39            False                     False
40            False                     False
41            False                     False
42            False                     False
43            False                     False
44            False                     False
45            False                     False
46            False                     False
47            False                     False
48            False                     False
49            False                     False

[50 rows x 37 columns]

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  """Entry point for launching an IPython kernel.
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  """Entry point for launching an IPython kernel.

TypeError: Cannot perform 'ror_' with a dtyped [bool] array and scalar of type [NoneType]

In [51]:
boston_df_out = dataset[~((dataset < (Q1 - 1.5 * IQR)) |(dataset > (Q3 + 1.5 * IQR))).any(axis=1)]
boston_df_out.shape

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  """Entry point for launching an IPython kernel.

(30, 37)

In [52]:

    quan=[]
    qual=[]
    for columnName in dataset.columns:
    #print(columnName)
        if(dataset[columnName].dtypes=='O'):
        #print("qual")
            qual.append(columnName)
        else:
        #print("quan")
             quan.append(columnName)

In [53]:
quan

['S.No',
 'Investment.1',
 'Profit.1',
 'Success/Failure',
 'IMDb Rating',
 'YouTube Views.1',
 'Common Background music',
 'Theme background Music',
 'No.of Part Released',
 'Comedy Scene',
 'Fast mode',
 'Slow mode',
 'Medium mode',
 'Pre-released song views.1',
 'YouTube Views.3',
 'First day Box office collection.1']

In [54]:
qual

['Film Industry',
 'Movie Name',
 'Genre',
 'Movie Release Date',
 'Investment',
 'Profit',
 'Trailer Released Date',
 'YouTube Views',
 '1st-30min',
 '2nd-30mins',
 '3rd-30mins',
 '4th-30mins',
 '5th-30mins',
 'Pre-released song views',
 'first song released date',
 'YouTube Views.2',
 'OTT',
 'Rating_Type',
 'Meme Marketing',
 'Critics_from_people ',
 'First day Box office collection']

In [55]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"]=np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
    descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]- descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]
    descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]
    descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"]
    descriptive[columnName]["Min"]=dataset[columnName].min()
    descriptive[columnName]["Max"]=dataset[columnName].max()

In [56]:
descriptive

,S.No,Investment.1,Profit.1,Success/Failure,IMDb Rating,YouTube Views.1,Common Background music,Theme background Music,No.of Part Released,Comedy Scene,Fast mode,Slow mode,Medium mode,Pre-released song views.1,YouTube Views.3,First day Box office collection.1
Mean,25.5,785660000.0,1081400000.0,0.5,6.44,10954060.0,0.54,0.48,3.52,1.0,0.14,0.04,0.82,14313620.0,29742258.0,118286000.0
Median,25.5,400000000.0,470000000.0,0.5,6.9,5250000.0,1.0,0.0,3.0,1.0,0.0,0.0,1.0,2050000.0,9150000.0,60000000.0
Mode,1,400000000,1000000000,0,8.0,10000000,1,0,3,1,0,0,1,2000000,50000000,60000000
Q1:25%,13.25,205000000.0,222500000.0,0.0,4.85,561750.0,0.0,0.0,3.0,1.0,0.0,0.0,1.0,1000000.0,3050000.0,20000000.0
Q2:50%,25.5,400000000.0,470000000.0,0.5,6.9,5250000.0,1.0,0.0,3.0,1.0,0.0,0.0,1.0,2050000.0,9150000.0,60000000.0
Q3:75%,37.75,700000000.0,1015000000.0,1.0,8.0,14000000.0,1.0,1.0,4.0,1.0,0.0,0.0,1.0,16000000.0,29750000.0,100000000.0
99%,49.51,5509999999.999998,7264999999.999997,1.0,9.155,59000000.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,105140000.0,302610000.0,911800000.0
Q4:100%,50.0,6000000000.0,8000000000.0,1.0,9.4,59000000.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,112000000.0,406000000.0,1000000000.0
IQR,24.5,495000000.0,792500000.0,1.0,3.15,13438250.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,15000000.0,26700000.0,80000000.0
1.5rule,36.75,742500000.0,1188750000.0,1.5,4.725,20157375.0,1.5,1.5,1.5,0.0,0.0,0.0,0.0,22500000.0,40050000.0,120000000.0
Lesser,-23.5,-537500000.0,-966250000.0,-1.5,0.125,-19595625.0,-1.5,-1.5,1.5,1.0,0.0,0.0,1.0,-21500000.0,-37000000.0,-100000000.0
Greater,74.5,1442500000.0,2203750000.0,2.5,12.725,34157375.0,2.5,2.5,5.5,1.0,0.0,0.0,1.0,38500000.0,69800000.0,220000000.0
Min,1,8000000,80000000,0,2.8,68000,0,0,2,1,0,0,0,12000,12900,6000000
Max,50,6000000000,8000000000,1,9.4,59000000,1,1,5,1,1,1,1,112000000,406000000,1000000000

In [57]:
lesser=[]
greater=[]
for colunName in quan:
    if(descriptive[colunName]["Min"]<descriptive[colunName]["Lesser"]):
        lesser.append(colunName)
    if(descriptive[colunName]["Max"]>descriptive[colunName]["Greater"]):
        greater.append(colunName)

In [58]:
lesser

['Medium mode']

In [59]:
greater

['Investment.1',
 'Profit.1',
 'YouTube Views.1',
 'Fast mode',
 'Slow mode',
 'Pre-released song views.1',
 'YouTube Views.3',
 'First day Box office collection.1']

In [72]:
for columnName in lesser:
    dataset[columnName][dataset[columnName]<descriptive[colunName]["Lesser"]]=descriptive[colunName]["Lesser"]
for columnName in greater:
    dataset[columnName][dataset[columnName]>descriptive[colunName]["Greater"]]=descriptive[colunName]["Greater"]

In [73]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=quan)
for columnName in quan:
    descriptive[columnName]["Mean"]=dataset[columnName].mean()
    descriptive[columnName]["Median"]=dataset[columnName].median()
    descriptive[columnName]["Mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"]=np.percentile(dataset[columnName],99)
    descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]
    descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]- descriptive[columnName]["Q1:25%"]
    descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]
    descriptive[columnName]["Lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]
    descriptive[columnName]["Greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"]
    descriptive[columnName]["Min"]=dataset[columnName].min()
    descriptive[columnName]["Max"]=dataset[columnName].max()

In [74]:
descriptive

,S.No,Investment.1,Profit.1,Success/Failure,IMDb Rating,YouTube Views.1,Common Background music,Theme background Music,No.of Part Released,Comedy Scene,Fast mode,Slow mode,Medium mode,Pre-released song views.1,YouTube Views.3,First day Box office collection.1
Mean,25.5,220000000.0,220000000.0,0.5,6.44,220000000.0,0.54,0.48,3.52,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
Median,25.5,220000000.0,220000000.0,0.5,6.9,220000000.0,1.0,0.0,3.0,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
Mode,1,220000000,220000000,0,8.0,220000000,1,0,3,1,220000000,220000000,-100000000,220000000,220000000,220000000
Q1:25%,13.25,220000000.0,220000000.0,0.0,4.85,220000000.0,0.0,0.0,3.0,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
Q2:50%,25.5,220000000.0,220000000.0,0.5,6.9,220000000.0,1.0,0.0,3.0,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
Q3:75%,37.75,220000000.0,220000000.0,1.0,8.0,220000000.0,1.0,1.0,4.0,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
99%,49.51,220000000.0,220000000.0,1.0,9.155,220000000.0,1.0,1.0,5.0,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
Q4:100%,50.0,220000000.0,220000000.0,1.0,9.4,220000000.0,1.0,1.0,5.0,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
IQR,24.5,0.0,0.0,1.0,3.15,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1.5rule,36.75,0.0,0.0,1.5,4.725,0.0,1.5,1.5,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lesser,-23.5,220000000.0,220000000.0,-1.5,0.125,220000000.0,-1.5,-1.5,1.5,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
Greater,74.5,220000000.0,220000000.0,2.5,12.725,220000000.0,2.5,2.5,5.5,1.0,220000000.0,220000000.0,-100000000.0,220000000.0,220000000.0,220000000.0
Min,1,220000000,220000000,0,2.8,220000000,0,0,2,1,220000000,220000000,-100000000,220000000,220000000,220000000
Max,50,220000000,220000000,1,9.4,220000000,1,1,5,1,220000000,220000000,-100000000,220000000,220000000,220000000

In [75]:
lesser=[]
greater=[]
for colunName in quan:
    if(descriptive[colunName]["Min"]<descriptive[colunName]["Lesser"]):
        lesser.append(colunName)
    if(descriptive[colunName]["Max"]>descriptive[colunName]["Greater"]):
        greater.append(colunName)

In [76]:
lesser

[]

In [77]:
greater

[]